#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8gb
#SBATCH --partition=hpg-turin
#SBATCH --gpus=1
#SBATCH --time=48:00:00
#SBATCH --output=%x.%j.out
#SBATCH --account=ruogu.fang
#SBATCH --qos=ruogu.fang

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh DME_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DME_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_multi_cls/checkpoint-00018.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DME_all_split_IRB2024_v5_2D_flash_attn_subtr0_multi_cls/checkpoint-00013.pth 5 AUC multi_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh CSR_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_CSR_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00024.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_CSR_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00029.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh Drusen_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Drusen_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00004.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Drusen_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00004.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh ERM_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_ERM_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00005.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_ERM_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00021.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh MH_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_MH_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00026.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_MH_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00052.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh CRVO_CRAO_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_CRVO_CRAO_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00005.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_CRVO_CRAO_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00099.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh PVD_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_PVD_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00069.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_PVD_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00009.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh RNV_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_RNV_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00039.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_RNV_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00027.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh DME_binary_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DME_binary_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00012.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DME_binary_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00046.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh PD_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_PD_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00050.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_PD_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00017.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh DKD_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DKD_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00042.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DKD_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00000.pth 2 AUC binary_cls

bash scripts/finetune_UFcohort_IRB2024v5_dualeval.sh Diabetes_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Diabetes_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_subtr0_binary_cls/checkpoint-00006.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Diabetes_all_split_IRB2024_v5_2D_flash_attn_subtr0_binary_cls/checkpoint-00033.pth 2 AUC binary_cls