#! /bin/bash

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh AMD_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_AMD_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_binary_cls/checkpoint-00007.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_AMD_all_split_IRB2024_v5_2D_flash_attn_binary_cls/checkpoint-00059.pth 2 AUPRC binary_cls

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh Cataract_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Cataract_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_binary_cls/checkpoint-00016.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Cataract_all_split_IRB2024_v5_2D_flash_attn_binary_cls/checkpoint-00031.pth 2 AUPRC binary_cls

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh DR_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DR_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_multi_cls/checkpoint-00015.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DR_all_split_IRB2024_v5_2D_flash_attn_multi_cls/checkpoint-00017.pth 6 AUPRC multi_cls

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh Glaucoma_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Glaucoma_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_multi_cls/checkpoint-00007.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Glaucoma_all_split_IRB2024_v5_2D_flash_attn_multi_cls/checkpoint-00014.pth 6 AUPRC multi_cls

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh DR_binary_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DR_binary_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_binary_cls/checkpoint-00034.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_DR_binary_all_split_IRB2024_v5_2D_flash_attn_binary_cls/checkpoint-00006.pth 2 AUPRC binary_cls

sbatch scripts/finetune_UFcohort_IRB2024v5_dualeval.sh Glaucoma_binary_all_split /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Glaucoma_binary_all_split_IRB2024_v5_3D_st_flash_attn_nodrop_binary_cls/checkpoint-00014.pth /orange/ruogu.fang/tienyuchang/OCTCube_results/outputs_ft_st/UFcohort_Glaucoma_binary_all_split_IRB2024_v5_2D_flash_attn_binary_cls/checkpoint-00025.pth 2 AUPRC binary_cls
